CREATE OR REPLACE FORCE EDITIONABLE VIEW "SMART_BI"."CRT_KER_04_STOCK" ("ENVIRONMENT", "UDM", "SKU", "QUALITY", "LOCATION", "QUANTITY", "SKU_TYPE", "INBOUND_DATE", "EAN", "MODEL", "PART", "COLOUR", "SIZE", "DROP", "PRODUCT_CATEGORY", "PRODUCT_SUBCATEGORY", "TECHNICAL_CLASS", "TECHNICAL_SUBCLASS", "STYLE_MATERIAL_VARIANT", "OD_ASSOCIATED", "ITEM_DESCRIPTION", "BRAND", "INBOUND_REFERENCE", "ASN", "BUILDING", "AISLE", "BUILDING_PHYSICAL", "LOCATION_TYPE", "SAP_VISIBILITY", "STORAGE_AREA", "REFLEX_RECEIPT_ID", "OWNER", "INVOICED_FLAG", "HANG_FLAT_FLAG", "CITES_FLAG", "DANGEROUS_FLAG", "ALCOHOL_FLAG", "PIECE_WEIGHT", "WEIGHT_UOM", "PIECE_HEIGHT", "PIECE_WIDTH", "PIECE_DEPTH", "PIECE_VOLUME", "VOLUME_UOM", "MADE_IN", "STORAGE_FAMILY", "PREPARATION_FAMILY", "UPDATED_DATE") AS 
  select  
'Reflex WEB B' 																																	AS "ENVIRONMENT" ,
sunsup as UDM,
CASKUC	as SKU,
gecqal as QUALITY,
emc1em||emc2em||emc3em||emc4em||emc5em as "LOCATION",
geqgei as QUANTITY,
CA.CASTNO as SKU_TYPE,
GEACRE||'/'||GEMCRE||'/'||GEJCRE as INBOUND_DATE,
VICIVL																																		    as "EAN" ,
CA.CALMOD																																		as "MODEL",
CA.CAPART																																		as "PART" ,
CA.CACOLC																																		as "COLOUR" ,
CA.CASIZC																																		as "SIZE",
CA.CADROP																																		as "DROP",
CA.CAPRCA																																		as "PRODUCT_CATEGORY" ,
CA.CAPRFA																																		as "PRODUCT_SUBCATEGORY" , 
CA.CADEGR																																		as "TECHNICAL_CLASS" , 
CA.CASUDE																																		as "TECHNICAL_SUBCLASS" ,
CA.CAMATN                                                                                                                                       as STYLE_MATERIAL_VARIANT,
CASE WHEN GE.GENPRL = 0 THEN 'NO' ELSE 'YES' END 																								AS "OD_ASSOCIATED",
CADESC	as ITEM_DESCRIPTION,
CABRDC	as BRAND,
RENBLF as INBOUND_REFERENCE,
RERREC as "ASN",
'B'																																				AS "BUILDING" ,
EMC1EM as AISLE,
CASE WHEN EMNEMP IN 3874 THEN 'B1'
     WHEN EMNEMP IN 3875 THEN 'B2'
    ELSE to_char(EMC5EM)
    END as BUILDING_PHYSICAL,
EMCTYE AS LOCATION_TYPE,
--TYLTYE as LOCATION_TYPE_DESIGNATION,
CASE WHEN 
   (TK03_DATETIME IS NULL AND O40TSTP IS NULL)  OR 
    SHCINV IS NOT NULL 
   OR GECQAL NOT IN ('1ST', 'QIN', 'TBR', 'PLO', 'EQI', 'RPL', 'ERP', '2ND', 'SPL', 'E2P', 'PPL', 'EPL', 'E1P', 'FRE', 'FPL', 'FPL', 'SHO', 'OVE', 'DAM', 'DPL', 'EDP', 'FRC', 'BCN')
   OR GECART NOT LIKE '8%'
   OR GECPRP NOT IN ('AMG', 'AMF', 'AMM', 'BAG', 'BAF', 'BAM', 'BVG', 'BVF', 'BVM', 'GUG', 'GUF', 'GUM', 'SLG', 'SLF', 'SLM')
   THEN 'NOT_VISIBLE'
   WHEN GECMBG IN ('PTW','RMQ') THEN 'VISIBLE_BLOCKED'
   ELSE 'VISIBLE' END AS SAP_VISIBILITY,
CASE WHEN EMC1EM LIKE '1S%' OR EMC1EM LIKE '2S%' THEN 'SHELVES'
   WHEN SUBSTR(EMC1EM,1,2) in ('0T','1T','2T','3T','1M') THEN 'MEZZANINE' 
   WHEN EMC1EM LIKE '0R%' THEN 'RACKS'
   WHEN (EMC1EM LIKE  '1G%' OR EMC1EM LIKE '2G%' OR EMC1EM LIKE '3G%' OR EMC1EM LIKE '0G%') THEN 'GOH'
   WHEN EMNEMP IN 3874 THEN 'DMS_STATIC' 
   WHEN EMNEMP IN 3875 THEN 'DMS_FLEX'
   WHEN EMC1EM LIKE '%CD' OR EMC1EM LIKE '%CS' THEN 'CONSIGNMENT'
   WHEN EMC1EM LIKE '0D%' THEN 'DANGEROUS'
   WHEN  (EMC1EM LIKE '1J%' OR EMC1EM LIKE '2J%' OR EMC1EM LIKE '3J%' OR EMC1EM LIKE '0J%') THEN 'JEWELRY'
   ELSE 'OTH'
   END AS "STORAGE_AREA",
lpad(GENANN,2,0) || '/' || lpad(GENREC,9,0) AS REFLEX_RECEIPT_ID,
GECPRP AS "OWNER",
CASE WHEN SHCINV IS NULL THEN 0 ELSE 1 END AS INVOICED_FLAG,
CAHFFG	as HANG_FLAT_FLAG,
CATCIT	as CITES_FLAG,
CAIHAM	as DANGEROUS_FLAG,
CAICAL	as ALCOHOL_FLAG,
CAPWGH	as PIECE_WEIGHT,
CAWTUM  as WEIGHT_UOM,
CAPHGH	as PIECE_HEIGHT,
CAPWID	as PIECE_WIDTH,
CAPDPT	as PIECE_DEPTH,
CAPVOL	as PIECE_VOLUME,
CAVUOM  as VOLUME_UOM,
CAMDIN	as MADE_IN,
VLCFAS as STORAGE_FAMILY,
VLCFPR as PREPARATION_FAMILY,
-- CASTNO	as "Style No",
-- CASDES	as "Size Description",
--GREATEST(
-- 		   nvl(GE.GGS_UPDATED,TIMESTAMP'1900-01-01 00:00:01'),           nvl(GE.GGS_CREATED ,TIMESTAMP'1900-01-01 00:00:01'),
--   		   nvl(SU.GGS_UPDATED,TIMESTAMP'1900-01-01 00:00:01'),           nvl(SU.GGS_CREATED ,TIMESTAMP'1900-01-01 00:00:01')
----   		   nvl(EM.GGS_UPDATED,TIMESTAMP'1900-01-01 00:00:01'),           nvl(EM.GGS_CREATED ,TIMESTAMP'1900-01-01 00:00:01')
--   		   )																																	AS "UPDATED_DATE"
null AS "UPDATED_DATE"
--'0'																																				AS "ISDELETED"
from hlgeinp@KE_IT_STB_GLOBE ge 
inner join hlsuppp@KE_IT_STB_GLOBE su on gensup=sunsup
inner join hlemplp@KE_IT_STB_GLOBE em on sunemp=emnemp 
LEFT  JOIN HLTYEMP@KE_IT_STB_GLOBE ty ON EMCTYE=TYCTYE
left  join HLRECPP@KE_IT_STB_GLOBE RE ON RE.recact=ge.gecact and RE.renann=ge.genann and ge.genrec=RE.renrec --and trunc(RE.GGS_DELETED) is null
right join kbcartp@KE_IT_STB_GLOBE CA on gecart=CASKUC --AND CA.GGS_DELETED IS null
left  join hlarvlp@KE_IT_STB_GLOBE VL on cacact = vlcact and caskuc = vlcart and vlcvla = '03' --AND VL.GGS_DELETED IS null
LEFT  JOIN
   -- Query per GEI ricevuti
     (SELECT CHCDPO, CHCACT, CHNANN, CHNREC, CHNANF, CHNRFI, MIN(CHDET3) AS TK03_DATETIME, MAX(CHDET3) AS TK03_DATETIME2 
      FROM KBRECHP@KE_IT_STB_GLOBE /*WHERE trunc(GGS_DELETED) is null*/ GROUP BY CHCDPO, CHCACT, CHNANN, CHNREC, CHNANF, CHNRFI
      )  INBOUND_INTERFACES ON CHCDPO=GECDPO AND CHCACT=GECACT AND CHNANF=GENANN AND CHNRFI=GENREC
LEFT  JOIN 
     -- Query per GEI invoice
      (SELECT shrdor,PRCNPRE,PRCCDPO,PRCCACT,PRCNCOL,SHCINV FROM HLPRCOP@KE_IT_STB_GLOBE INNER JOIN KBSHIPP@KE_IT_STB_GLOBE Y ON PRCCACT=SHCACT AND PRCCDPO=SHCDEP AND PRCNANN=SHNANN AND PRCNPRE=SHNPRP
      WHERE SHCINV NOT IN ' ' --and trunc(Y.GGS_DELETED) is null
      GROUP BY PRCNCOL,SHCINV,PRCCDPO,PRCCACT,PRCNPRE,shrdor)
      ON GECACT=PRCCACT AND GECDPO=PRCCDPO AND GENCOL=PRCNCOL 
  LEFT JOIN XPSTOCP@KE_IT_STB_GLOBE ON O40NGEI=GENGEI
  LEFT JOIN (
      SELECT h1.*
      FROM HLVLIDP@KE_IT_STB_GLOBE h1
      INNER JOIN (
          SELECT MAX(VIACRE || LPAD(VIMCRE, 2, '0') || LPAD(VIJCRE, 2, '0') || LPAD(VIHCRE, 6, '0')) AS max_value, VICART
          FROM HLVLIDP@KE_IT_STB_GLOBE
          WHERE VICTYI = 'EAN13' -- and trunc(GGS_DELETED) is null
          GROUP BY VICART
      ) h2
      ON (h1.VIACRE || LPAD(h1.VIMCRE, 2, '0') || LPAD(h1.VIJCRE, 2, '0') || LPAD(h1.VIHCRE, 6, '0')) = h2.max_value
      AND h1.VICART = h2.VICART
      WHERE h1.VICTYI = 'EAN13' /*and trunc(h1.GGS_DELETED) is null*/) ON VICACT=CACACT AND VICART=CASKUC
   WHERE 1=1 AND GE.GECACT = '100' AND GE.GECDPO = '001' 
   AND GE.GECTST IN ('200');