CREATE TABLE "SMART_BI"."FACT_KER_04_STOCK" 
   (	"FACT_KER_04_STOCKID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ENVIRONMENT" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"UDM" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"SKU" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"QUALITY" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"LOCATION" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"QUANTITY" NUMBER(38,0) DEFAULT 0, 
	"SKU_TYPE" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"INBOUND_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"EAN" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"MODEL" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"PART" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"COLOUR" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"SIZE" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"DROP" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"PRODUCT_CATEGORY" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"PRODUCT_SUBCATEGORY" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"TECHNICAL_CLASS" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"TECHNICAL_SUBCLASS" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"STYLE_MATERIAL_VARIANT" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"OD_ASSOCIATED" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"ITEM_DESCRIPTION" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"BRAND" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"INBOUND_REFERENCE" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"ASN" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"BUILDING" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"AISLE" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"BUILDING_PHYSICAL" VARCHAR2(10 CHAR) DEFAULT 'Not Set', 
	"LOCATION_TYPE" VARCHAR2(10 CHAR) DEFAULT 'Not Set', 
	"SAP_VISIBILITY" VARCHAR2(20 CHAR) DEFAULT 'Not Set', 
	"STORAGE_AREA" VARCHAR2(20 CHAR) DEFAULT 'Not Set', 
	"REFLEX_RECEIPT_ID" VARCHAR2(20 CHAR) DEFAULT 'Not Set', 
	"OWNER" VARCHAR2(10 CHAR) DEFAULT 'Not Set', 
	"INVOICED_FLAG" NUMBER DEFAULT 0, 
	"HANG_FLAT_FLAG" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"CITES_FLAG" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"DANGEROUS_FLAG" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"ALCOHOL_FLAG" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"PIECE_WEIGHT" NUMBER(22,3) DEFAULT 0, 
	"WEIGHT_UOM" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"PIECE_HEIGHT" NUMBER(22,3) DEFAULT 0, 
	"PIECE_WIDTH" NUMBER(22,3) DEFAULT 0, 
	"PIECE_DEPTH" NUMBER(22,3) DEFAULT 0, 
	"PIECE_VOLUME" NUMBER(22,3) DEFAULT 0, 
	"VOLUME_UOM" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"MADE_IN" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"STORAGE_FAMILY" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"PREPARATION_FAMILY" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SMART_BI_DATA" ;
  ALTER TABLE "SMART_BI"."FACT_KER_04_STOCK" ADD CONSTRAINT "FACT_KER_04_STOCK_NFBJLNXTNF" PRIMARY KEY ("FACT_KER_04_STOCKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SMART_BI_DATA"  ENABLE;