CREATE TABLE "SMART_BI"."FACT_KER_02_OUTBOUND_VAS" 
   (	"P1CDPO" NVARCHAR2(3) NOT NULL ENABLE, 
	"P1CACT" NVARCHAR2(3) NOT NULL ENABLE, 
	"P1NANP" NUMBER(2,0) NOT NULL ENABLE, 
	"P1NPRE" NUMBER(9,0) NOT NULL ENABLE, 
	"PREPA_TYPE" VARCHAR2(6 CHAR), 
	"VAS_CODE" VARCHAR2(4000 CHAR), 
	"VAS_CLUSTER" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SMART_BI_DATA" ;
  ALTER TABLE "SMART_BI"."FACT_KER_02_OUTBOUND_VAS" ADD CONSTRAINT "FACT_KER_02_OUTBOUND_VAS_PK" PRIMARY KEY ("P1CDPO", "P1CACT", "P1NANP", "P1NPRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SMART_BI_DATA"  ENABLE;