CREATE TABLE "SMART_BI"."FACT_KER_01_INBOUND" 
   (	"PK_FACT_INBOUND" RAW(16) NOT NULL ENABLE, 
	"ENVIRONMENT" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"QUALITY" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"UDM" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"SKU" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"INBOUND_REFERENCE" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"ASN" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"FORECAST_QUANTITY" NUMBER(22,3) DEFAULT 0, 
	"ACTUAL_QUANTITY" NUMBER(22,3) DEFAULT 0, 
	"EAN" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"MODEL" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"PART" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"COLOUR" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"SIZE" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"DROP" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"PRODUCT_CATEGORY" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"PRODUCT_SUBCATEGORY" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"TRUCK_PLATE" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"BUILDING" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"DOCK" VARCHAR2(100 CHAR) DEFAULT 'Not Set', 
	"TRUCK_GATE_ARRIVAL" TIMESTAMP (6), 
	"TRUCK_BAY_ARRIVAL" TIMESTAMP (6), 
	"TRUCK_BAY_DEPARTURE" TIMESTAMP (6), 
	"TRUCK_GATE_DEPARTURE" TIMESTAMP (6), 
	"UDM_RECEIVING" TIMESTAMP (6), 
	"UDM_POSITIONING" TIMESTAMP (6), 
	"APPOINTMENT_DATE" TIMESTAMP (6), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ISDELETED" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SMART_BI_DATA" ;
  ALTER TABLE "SMART_BI"."FACT_KER_01_INBOUND" ADD CONSTRAINT "FACT_KER_01_INBOUND_PK2" PRIMARY KEY ("PK_FACT_INBOUND")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SMART_BI_DATA"  ENABLE;