CREATE TABLE "SMART_BI"."FACT_KER_03_SATURATION_IS" 
   (	"PK_FACT_SATURATION" RAW(16) NOT NULL ENABLE, 
	"ENVIRONMENT" VARCHAR2(100 CHAR), 
	"ORDER_ID" VARCHAR2(100 CHAR), 
	"SEQUENCE_NUMBER" VARCHAR2(100 CHAR), 
	"UDM" VARCHAR2(100 CHAR), 
	"SKU" VARCHAR2(100 CHAR), 
	"QUALITY" VARCHAR2(100 CHAR), 
	"SKU_VOLUME" NUMBER(22,3), 
	"SKU_WEIGHT" NUMBER(22,3), 
	"QUANTITY" NUMBER(38,0), 
	"SKU_TYPE" VARCHAR2(100 CHAR), 
	"PRODUCT_CATEGORY" VARCHAR2(100 CHAR), 
	"ARTICLE_SUBCLASS" VARCHAR2(100 CHAR), 
	"FLAG_HAZMAT_SKU" VARCHAR2(100 CHAR), 
	"FLAG_FSC_SKU" VARCHAR2(100 CHAR), 
	"FLAG_JEWELLERY_SKU" VARCHAR2(100 CHAR), 
	"FLAG_PACKAGING_JEWELLERY_SKU" VARCHAR2(100 CHAR), 
	"FLAG_HALMARKING_SKU" VARCHAR2(100 CHAR), 
	"FLAG_CITES_SKU" VARCHAR2(100 CHAR), 
	"FLAG_CEE_SKU" VARCHAR2(100 CHAR), 
	"PARCEL_TYPE_FORECAST" VARCHAR2(100 CHAR), 
	"PARCEL_TYPE_ORDERINSUPDATE" VARCHAR2(100 CHAR), 
	"PARCEL_TYPE_ACTUAL" VARCHAR2(100 CHAR), 
	"INTERNAL_HEIGHT_PARCEL_FORECAST" NUMBER(22,3), 
	"INTERNAL_WIDTH_PARCEL_FORECAST" NUMBER(22,3), 
	"INTERNAL_LENGTH_PARCEL_FORECAST" NUMBER(22,3), 
	"INTERNAL_VOLUME_PARCEL_FORECAST" NUMBER(22,3), 
	"EXTERNAL_HEIGHT_PARCEL_FORECAST" NUMBER(22,3), 
	"EXTERNAL_WIDTH_PARCEL_FORECAST" NUMBER(22,3), 
	"EXTERNAL_LENGTH_PARCEL_FORECAST" NUMBER(22,3), 
	"EXTERNAL_VOLUME_PARCEL_FORECAST" NUMBER(22,3), 
	"INTERNAL_HEIGHT_PARCEL_ACTUAL" NUMBER(22,3), 
	"INTERNAL_WIDTH_PARCEL_ACTUAL" NUMBER(22,3), 
	"INTERNAL_LENGTH_PARCEL_ACTUAL" NUMBER(22,3), 
	"INTERNAL_VOLUME_PARCEL_ACTUAL" NUMBER(22,3), 
	"EXTERNAL_HEIGHT_PARCEL_ACTUAL" NUMBER(22,3), 
	"EXTERNAL_WIDTH_PARCEL_ACTUAL" NUMBER(22,3), 
	"EXTERNAL_LENGTH_PARCEL_ACTUAL" NUMBER(22,3), 
	"EXTERNAL_VOLUME_PARCEL_ACTUAL" NUMBER(22,3), 
	"PIECES_WEIGHT" NUMBER(22,3), 
	"EMPTY_PARCEL_WEIGHT" NUMBER(22,3), 
	"PARCEL_WEIGHT" NUMBER(22,3), 
	"INTEGRATION_DATE" TIMESTAMP (6), 
	"TK05_PACKED_DATE" TIMESTAMP (6), 
	"BUILDING_NAME" VARCHAR2(100 CHAR), 
	"PACKING_STATION_ID" VARCHAR2(100 CHAR), 
	"PACKING_USER" VARCHAR2(100 CHAR), 
	"CUSTOMER_CODE" VARCHAR2(100 CHAR), 
	"COUNTRY" VARCHAR2(100 CHAR), 
	"FLOW" VARCHAR2(100 CHAR), 
	"CHANNEL" VARCHAR2(100 CHAR), 
	"BRAND" VARCHAR2(100 CHAR), 
	"REFLEX_ORDER" VARCHAR2(100 CHAR), 
	"REFLEX_PREPERATION" VARCHAR2(100 CHAR), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_DATE" TIMESTAMP (6), 
	"ISDELETED" NUMBER, 
	"UPDATED_DATE_ORACLE" TIMESTAMP (6), 
	"CARTON_LINE_SEQUENCE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SMART_BI_DATA" ;
  ALTER TABLE "SMART_BI"."FACT_KER_03_SATURATION_IS" ADD CONSTRAINT "FACT_KER_03_SATURATION_IS_UAT_PK" PRIMARY KEY ("PK_FACT_SATURATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SMART_BI_DATA"  ENABLE;